### ISSUE TITLE
Recent design section content overlaps to header when scrolling

### ISSUE THREAD

**Issue by Kerlwin008** [Ikal-Sama/next-portfolio#1]
**Description**
When scrolling down to recent design section, the contents including the arrows overlaps to the top navigation bar.

**Screenshots**
Desktop: https://gyazo.com/2f845e520a76d5569b47ea7badaefd65
Mobile: https://gyazo.com/4d562cedce8ad283d0769c74a0ebe08b

**Comment by Ikal-Sama** [comment]
I am sorry Mr Arsolon, thank you for pointing that out, i will fix it
immediately.
